### Label Encoder

In [12]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [13]:
data =pd.read_csv("D:/DS Files/DS Assingments/Excel Data Sheets/iris.csv",index_col=0)

In [14]:
data.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

In [15]:
#Changes does not effect the "data" dataframe
data1=data.copy()

In [16]:
labelencoder = LabelEncoder()
data1.iloc[:, -1] = labelencoder.fit_transform(data1.iloc[:,-1])

In [17]:
data1

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
1             5.1          3.5           1.4          0.2        0
2             4.9          3.0           1.4          0.2        0
3             4.7          3.2           1.3          0.2        0
4             4.6          3.1           1.5          0.2        0
5             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
146           6.7          3.0           5.2          2.3        2
147           6.3          2.5           5.0          1.9        2
148           6.5          3.0           5.2          2.0        2
149           6.2          3.4           5.4          2.3        2
150           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

### One Hot Encoder

#### Using sklearn

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
data2=pd.read_csv("D:/DS Files/DS Assingments/Excel Data Sheets/iris.csv",index_col=0)

In [20]:
data2

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
1             5.1          3.5           1.4          0.2     setosa
2             4.9          3.0           1.4          0.2     setosa
3             4.7          3.2           1.3          0.2     setosa
4             4.6          3.1           1.5          0.2     setosa
5             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
146           6.7          3.0           5.2          2.3  virginica
147           6.3          2.5           5.0          1.9  virginica
148           6.5          3.0           5.2          2.0  virginica
149           6.2          3.4           5.4          2.3  virginica
150           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [21]:
# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')

In [22]:
# passing bridge-types-cat column (label encoded values of bridge_types)
enc_df = pd.DataFrame(enc.fit_transform(data2[['Species']]).toarray())

In [23]:
enc.fit_transform(data2[['Species']])

<150x3 sparse matrix of type '<class 'numpy.float64'>'
	with 150 stored elements in Compressed Sparse Row format>

In [24]:
enc_df

       0    1    2
0    1.0  0.0  0.0
1    1.0  0.0  0.0
2    1.0  0.0  0.0
3    1.0  0.0  0.0
4    1.0  0.0  0.0
..   ...  ...  ...
145  0.0  0.0  1.0
146  0.0  0.0  1.0
147  0.0  0.0  1.0
148  0.0  0.0  1.0
149  0.0  0.0  1.0

[150 rows x 3 columns]

In [25]:
# merge with main df 
data_final = data2.iloc[:,0:4].join(enc_df)
data_final

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    0    1    2
1             5.1          3.5           1.4          0.2  1.0  0.0  0.0
2             4.9          3.0           1.4          0.2  1.0  0.0  0.0
3             4.7          3.2           1.3          0.2  1.0  0.0  0.0
4             4.6          3.1           1.5          0.2  1.0  0.0  0.0
5             5.0          3.6           1.4          0.2  1.0  0.0  0.0
..            ...          ...           ...          ...  ...  ...  ...
146           6.7          3.0           5.2          2.3  0.0  0.0  1.0
147           6.3          2.5           5.0          1.9  0.0  0.0  1.0
148           6.5          3.0           5.2          2.0  0.0  0.0  1.0
149           6.2          3.4           5.4          2.3  0.0  0.0  1.0
150           5.9          3.0           5.1          1.8  NaN  NaN  NaN

[150 rows x 7 columns]

#### Using Pandas

In [26]:
import pandas as pd

In [27]:
data3 =pd.read_csv("D:/DS Files/DS Assingments/Excel Data Sheets/iris.csv",index_col=0)

In [28]:
data_encoded=pd.get_dummies(data3)

In [29]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
1,5.1,3.5,1.4,0.2,1,0,0
2,4.9,3.0,1.4,0.2,1,0,0
3,4.7,3.2,1.3,0.2,1,0,0
4,4.6,3.1,1.5,0.2,1,0,0
5,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
146,6.7,3.0,5.2,2.3,0,0,1
147,6.3,2.5,5.0,1.9,0,0,1
148,6.5,3.0,5.2,2.0,0,0,1
149,6.2,3.4,5.4,2.3,0,0,1
150,5.9,3.0,5.1,1.8,0,0,1

#### IsolationForest

In [30]:
from sklearn.ensemble import IsolationForest

In [31]:
data =pd.read_csv("D:/DS Files/DS Assingments/Excel Data Sheets/iris.csv",index_col=0)
data_encoded=pd.get_dummies(data)

In [32]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
1,5.1,3.5,1.4,0.2,1,0,0
2,4.9,3.0,1.4,0.2,1,0,0
3,4.7,3.2,1.3,0.2,1,0,0
4,4.6,3.1,1.5,0.2,1,0,0
5,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
146,6.7,3.0,5.2,2.3,0,0,1
147,6.3,2.5,5.0,1.9,0,0,1
148,6.5,3.0,5.2,2.0,0,0,1
149,6.2,3.4,5.4,2.3,0,0,1
150,5.9,3.0,5.1,1.8,0,0,1

In [33]:
# training the model
clf = IsolationForest(n_estimators=200,random_state=10,contamination=.01)
clf.fit(data_encoded)

IsolationForest(contamination=0.01, n_estimators=200, random_state=10)

In [34]:
help(IsolationForest())

Help on IsolationForest in module sklearn.ensemble._iforest object:

class IsolationForest(sklearn.base.OutlierMixin, sklearn.ensemble._bagging.BaseBagging)
 |  IsolationForest(*, n_estimators=100, max_samples='auto', contamination='auto', max_features=1.0, bootstrap=False, n_jobs=None, random_state=None, verbose=0, warm_start=False)
 |
 |  Isolation Forest Algorithm.
 |
 |  Return the anomaly score of each sample using the IsolationForest algorithm
 |
 |  The IsolationForest 'isolates' observations by randomly selecting a feature
 |  and then randomly selecting a split value between the maximum and minimum
 |  values of the selected feature.
 |
 |  Since recursive partitioning can be represented by a tree structure, the
 |  number of splittings required to isolate a sample is equivalent to the path
 |  length from the root node to the terminating node.
 |
 |  This path length, averaged over a forest of such random trees, is a
 |  measure of normality and our decision function.
 |
 |  Random partitioning produces noticeably shorter paths for anomalies.
 |  Hence, when a forest of random trees collectively produce shorter path
 |  lengths for particular samples, they are highly likely to be anomalies.
 |
 |  Read more in the :ref:`User Guide <isolation_forest>`.
 |
 |  .. versionadded:: 0.18
 |
 |  Parameters
 |  ----------
 |  n_estimators : int, default=100
 |      The number of base estimators in the ensemble.
 |
 |  max_samples : "auto", int or float, default="auto"
 |      The number of samples to draw from X to train each base estimator.
 |          - If int, then draw `max_samples` samples.
 |          - If float, then draw `max_samples * X.shape[0]` samples.
 |          - If "auto", then `max_samples=min(256, n_samples)`.
 |
 |      If max_samples is larger than the number of samples provided,
 |      all samples will be used for all trees (no sampling).
 |
 |  contamination : 'auto' or float, default='auto'
 |      The amount of contamination of the data set, i.e. the proportion
 |      of outliers in the data set. Used when fitting to define the threshold
 |      on the scores of the samples.
 |
 |          - If 'auto', the threshold is determined as in the
 |            original paper.
 |          - If float, the contamination should be in the range [0, 0.5].
 |
 |      .. versionchanged:: 0.22
 |         The default value of ``contamination`` changed from 0.1
 |         to ``'auto'``.
 |
 |  max_features : int or float, default=1.0
 |      The number of features to draw from X to train each base estimator.
 |
 |          - If int, then draw `max_features` features.
 |          - If float, then draw `max_features * X.shape[1]` features.
 |
 |  bootstrap : bool, default=False
 |      If True, individual trees are fit on random subsets of the training
 |      data sampled with replacement. If False, sampling without replacement
 |      is performed.
 |
 |  n_jobs : int, default=None
 |      The number of jobs to run in parallel for both :meth:`fit` and
 |      :meth:`predict`. ``None`` means 1 unless in a
 |      :obj:`joblib.parallel_backend` context. ``-1`` means using all
 |      processors. See :term:`Glossary <n_jobs>` for more details.
 |
 |  random_state : int, RandomState instance or None, default=None
 |      Controls the pseudo-randomness of the selection of the feature
 |      and split values for each branching step and each tree in the forest.
 |
 |      Pass an int for reproducible results across multiple function calls.
 |      See :term:`Glossary <random_state>`.
 |
 |  verbose : int, default=0
 |      Controls the verbosity of the tree building process.
 |
 |  warm_start : bool, default=False
 |      When set to ``True``, reuse the solution of the previous call to fit
 |      and add more estimators to the ensemble, otherwise, just fit a whole
 |      new forest. See :term:`the Glossary <warm_start>`.
 |
 |      .. versionadded:: 0.21
 |
 |  Attributes
 |  ----------
 |  base_estimator_ : ExtraTreeRegressor instance
 |      The child estimator template used to create the collection of
 |      fitted sub-estimators.
 |
 |  estimators_ : list of ExtraTreeRegressor instances
 |      The collection of fitted sub-estimators.
 |
 |  estimators_features_ : list of ndarray
 |      The subset of drawn features for each base estimator.
 |
 |  estimators_samples_ : list of ndarray
 |      The subset of drawn samples (i.e., the in-bag samples) for each base
 |      estimator.
 |
 |  max_samples_ : int
 |      The actual number of samples.
 |
 |  offset_ : float
 |      Offset used to define the decision function from the raw scores. We
 |      have the relation: ``decision_function = score_samples - offset_``.
 |      ``offset_`` is defined as follows. When the contamination parameter is
 |      set to "auto", the offset is equal to -0.5 as the scores of inliers are
 |      close to 0 and the scores of outliers are close to -1. When a
 |      contamination parameter different than "auto" is provided, the offset
 |      is defined in such a way we obtain the expected number of outliers
 |      (samples with decision function < 0) in training.
 |
 |      .. versionadded:: 0.20
 |
 |  n_features_ : int
 |      The number of features when ``fit`` is performed.
 |
 |  Notes
 |  -----
 |  The implementation is based on an ensemble of ExtraTreeRegressor. The
 |  maximum depth of each tree is set to ``ceil(log_2(n))`` where
 |  :math:`n` is the number of samples used to build the tree
 |  (see (Liu et al., 2008) for more details).
 |
 |  References
 |  ----------
 |  .. [1] Liu, Fei Tony, Ting, Kai Ming and Zhou, Zhi-Hua. "Isolation forest."
 |         Data Mining, 2008. ICDM'08. Eighth IEEE International Conference on.
 |  .. [2] Liu, Fei Tony, Ting, Kai Ming and Zhou, Zhi-Hua. "Isolation-based
 |         anomaly detection." ACM Transactions on Knowledge Discovery from
 |         Data (TKDD) 6.1 (2012): 3.
 |
 |  See Also
 |  ----------
 |  sklearn.covariance.EllipticEnvelope : An object for detecting outliers in a
 |      Gaussian distributed dataset.
 |  sklearn.svm.OneClassSVM : Unsupervised Outlier Detection.
 |      Estimate the support of a high-dimensional distribution.
 |      The implementation is based on libsvm.
 |  sklearn.neighbors.LocalOutlierFactor : Unsupervised Outlier Detection
 |      using Local Outlier Factor (LOF).
 |
 |  Examples
 |  --------
 |  >>> from sklearn.ensemble import IsolationForest
 |  >>> X = [[-1.1], [0.3], [0.5], [100]]
 |  >>> clf = IsolationForest(random_state=0).fit(X)
 |  >>> clf.predict([[0.1], [0], [90]])
 |  array([ 1,  1, -1])
 |
 |  Method resolution order:
 |      IsolationForest
 |      sklearn.base.OutlierMixin
 |      sklearn.ensemble._bagging.BaseBagging
 |      sklearn.ensemble._base.BaseEnsemble
 |      sklearn.base.MetaEstimatorMixin
 |      sklearn.base.BaseEstimator
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, *, n_estimators=100, max_samples='auto', contamination='auto', max_features=1.0, bootstrap=False, n_jobs=None, random_state=None, verbose=0, warm_start=False)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  decision_function(self, X)
 |      Average anomaly score of X of the base classifiers.
 |
 |      The anomaly score of an input sample is computed as
 |      the mean anomaly score of the trees in the forest.
 |
 |      The measure of normality of an observation given a tree is the depth
 |      of the leaf containing this observation, which is equivalent to
 |      the number of splittings required to isolate this point. In case of
 |      several observations n_left in the leaf, the average path length of
 |      a n_left samples isolation tree is added.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The input samples. Internally, it will be converted to
 |          ``dtype=np.float32`` and if a sparse matrix is provided
 |          to a sparse ``csr_matrix``.
 |
 |      Returns
 |      -------
 |      scores : ndarray of shape (n_samples,)
 |          The anomaly score of the input samples.
 |          The lower, the more abnormal. Negative scores represent outliers,
 |          positive scores represent inliers.
 |
 |  fit(self, X, y=None, sample_weight=None)
 |      Fit estimator.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The input samples. Use ``dtype=np.float32`` for maximum
 |          efficiency. Sparse matrices are also supported, use sparse
 |          ``csc_matrix`` for maximum efficiency.
 |
 |      y : Ignored
 |          Not used, present for API consistency by convention.
 |
 |      sample_weight : array-like of shape (n_samples,), default=None
 |          Sample weights. If None, then samples are equally weighted.
 |
 |      Returns
 |      -------
 |      self : object
 |          Fitted estimator.
 |
 |  predict(self, X)
 |      Predict if a particular sample is an outlier or not.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The input samples. Internally, it will be converted to
 |          ``dtype=np.float32`` and if a sparse matrix is provided
 |          to a sparse ``csr_matrix``.
 |
 |      Returns
 |      -------
 |      is_inlier : ndarray of shape (n_samples,)
 |          For each observation, tells whether or not (+1 or -1) it should
 |          be considered as an inlier according to the fitted model.
 |
 |  score_samples(self, X)
 |      Opposite of the anomaly score defined in the original paper.
 |
 |      The anomaly score of an input sample is computed as
 |      the mean anomaly score of the trees in the forest.
 |
 |      The measure of normality of an observation given a tree is the depth
 |      of the leaf containing this observation, which is equivalent to
 |      the number of splittings required to isolate this point. In case of
 |      several observations n_left in the leaf, the average path length of
 |      a n_left samples isolation tree is added.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The input samples.
 |
 |      Returns
 |      -------
 |      scores : ndarray of shape (n_samples,)
 |          The anomaly score of the input samples.
 |          The lower, the more abnormal.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __abstractmethods__ = frozenset()
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.OutlierMixin:
 |
 |  fit_predict(self, X, y=None)
 |      Perform fit on X and returns labels for X.
 |
 |      Returns -1 for outliers and 1 for inliers.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix, dataframe} of shape             (n_samples, n_features)
 |
 |      y : Ignored
 |          Not used, present for API consistency by convention.
 |
 |      Returns
 |      -------
 |      y : ndarray of shape (n_samples,)
 |          1 for inliers, -1 for outliers.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from sklearn.base.OutlierMixin:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from sklearn.ensemble._bagging.BaseBagging:
 |
 |  estimators_samples_
 |      The subset of drawn samples for each base estimator.
 |
 |      Returns a dynamically generated list of indices identifying
 |      the samples used for fitting each member of the ensemble, i.e.,
 |      the in-bag samples.
 |
 |      Note: the list is re-created at each call to the property in order
 |      to reduce the object memory footprint by not storing the sampling
 |      data. Thus fetching the property may be slower than expected.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.ensemble._base.BaseEnsemble:
 |
 |  __getitem__(self, index)
 |      Return the index'th estimator in the ensemble.
 |
 |  __iter__(self)
 |      Return iterator over estimators in the ensemble.
 |
 |  __len__(self)
 |      Return the number of estimators in the ensemble.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from sklearn.ensemble._base.BaseEnsemble:
 |
 |  __annotations__ = {'_required_parameters': typing.List[str]}
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.BaseEstimator:
 |
 |  __getstate__(self)
 |
 |  __repr__(self, N_CHAR_MAX=700)
 |      Return repr(self).
 |
 |  __setstate__(self, state)
 |
 |  get_params(self, deep=True)
 |      Get parameters for this estimator.
 |
 |      Parameters
 |      ----------
 |      deep : bool, default=True
 |          If True, will return the parameters for this estimator and
 |          contained subobjects that are estimators.
 |
 |      Returns
 |      -------
 |      params : dict
 |          Parameter names mapped to their values.
 |
 |  set_params(self, **params)
 |      Set the parameters of this estimator.
 |
 |      The method works on simple estimators as well as on nested objects
 |      (such as :class:`~sklearn.pipeline.Pipeline`). The latter have
 |      parameters of the form ``<component>__<parameter>`` so that it's
 |      possible to update each component of a nested object.
 |
 |      Parameters
 |      ----------
 |      **params : dict
 |          Estimator parameters.
 |
 |      Returns
 |      -------
 |      self : estimator instance
 |          Estimator instance.

In [35]:

# predictions
y_pred_outliers = clf.predict(data_encoded)

In [36]:
#-1 for outliers and 1 for inliers.
y_pred_outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [37]:
data_encoded.loc[y_pred_outliers==-1]

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
107,4.9,2.5,4.5,1.7,0,0,1
119,7.7,2.6,6.9,2.3,0,0,1

In [38]:
## Let us add a new data point which is outlier
data_encoded.loc[151]=[20,40,30,50,1,0,0]

In [39]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
1,5.1,3.5,1.4,0.2,1,0,0
2,4.9,3.0,1.4,0.2,1,0,0
3,4.7,3.2,1.3,0.2,1,0,0
4,4.6,3.1,1.5,0.2,1,0,0
5,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
147,6.3,2.5,5.0,1.9,0,0,1
148,6.5,3.0,5.2,2.0,0,0,1
149,6.2,3.4,5.4,2.3,0,0,1
150,5.9,3.0,5.1,1.8,0,0,1
151,20.0,40.0,30.0,50.0,1,0,0

In [40]:
# training the model
clf = IsolationForest(random_state=10,contamination=.01)
clf.fit(data_encoded)
# predictions
y_pred_outliers = clf.predict(data_encoded)
y_pred_outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1])

In [41]:
data_encoded.loc[y_pred_outliers==-1]

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
107,4.9,2.5,4.5,1.7,0,0,1
151,20.0,40.0,30.0,50.0,1,0,0

In [42]:
data_encoded['scores']=clf.decision_function(data_encoded)

In [50]:
data_encoded['anomaly']=clf.predict(data_encoded.iloc[:,0:7])

In [44]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica,scores,anomaly
1,5.1,3.5,1.4,0.2,1,0,0,0.201438,1
2,4.9,3.0,1.4,0.2,1,0,0,0.183516,1
3,4.7,3.2,1.3,0.2,1,0,0,0.173272,1
4,4.6,3.1,1.5,0.2,1,0,0,0.181867,1
5,5.0,3.6,1.4,0.2,1,0,0,0.198218,1
...,...,...,...,...,...,...,...,...,...
147,6.3,2.5,5.0,1.9,0,0,1,0.134374,1
148,6.5,3.0,5.2,2.0,0,0,1,0.178850,1
149,6.2,3.4,5.4,2.3,0,0,1,0.122817,1
150,5.9,3.0,5.1,1.8,0,0,1,0.156061,1
151,20.0,40.0,30.0,50.0,1,0,0,-0.287729,-1

In [45]:
#Print the outlier data points
data_encoded[data_encoded['anomaly']==-1]

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica,scores,anomaly
107,4.9,2.5,4.5,1.7,0,0,1,-0.008763,-1
151,20.0,40.0,30.0,50.0,1,0,0,-0.287729,-1

### PPS score

In [46]:
#install the package
!pip install ppscore

Collecting ppscore
  Downloading ppscore-1.2.0.tar.gz (47 kB)
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in e:\anaconda\lib\site-packages (from ppscore) (1.2.4)
Requirement already satisfied: scikit-learn<1.0.0,>=0.20.2 in e:\anaconda\lib\site-packages (from ppscore) (0.24.1)
Requirement already satisfied: pytz>=2017.3 in e:\anaconda\lib\site-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in e:\anaconda\lib\site-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.8.1)
Requirement already satisfied: numpy>=1.16.5 in e:\anaconda\lib\site-packages (from pandas<2.0.0,>=1.0.0->ppscore) (1.20.1)
Requirement already satisfied: six>=1.5 in e:\anaconda\lib\site-packages (from python-dateutil>=2.7.3->pandas<2.0.0,>=1.0.0->ppscore) (1.15.0)
Requirement already satisfied: scipy>=0.19.1 in e:\anaconda\lib\site-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (1.6.2)
Requirement already satisfied: joblib>=0.11 in e:\anaconda\lib\site-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in e:\anaconda\lib\site-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (2.1.0)
Building wheels for collected packages: ppscore
  Building wheel for ppscore (setup.py): started
  Building wheel for ppscore (setup.py): finished with status 'done'
  Created wheel for ppscore: filename=ppscore-1.2.0-py2.py3-none-any.whl size=13050 sha256=952c2f5e5e9476445dbb646c8a515963770be339b549dea5c8d18ba50121d721
  Stored in directory: c:\users\dell\appdata\local\pip\cache\wheels\fb\0e\65\da65ce669381fc01b6ef990d301d3586991f89bff1175877a4
Successfully built ppscore
Installing collected packages: ppscore
Successfully installed ppscore-1.2.0

In [47]:
import ppscore as pps

In [48]:
#pps.score(df, "feature_column", "target_column")  syntax
pps.score(data, "Petal.Length", "Sepal.Length")

{'x': 'Petal.Length',
 'y': 'Sepal.Length',
 'ppscore': 0.5256173335370536,
 'case': 'regression',
 'is_valid_score': True,
 'metric': 'mean absolute error',
 'baseline_score': 0.6846666666666668,
 'model_score': 0.32479399897163064,
 'model': DecisionTreeRegressor()}

In [49]:
#calculate the whole PPS matrix
pps.matrix(data)

,x,y,ppscore,case,is_valid_score,metric,baseline_score,model_score,model
0,Sepal.Length,Sepal.Length,1.000000,predict_itself,True,None,0.000000,1.000000,None
1,Sepal.Length,Sepal.Width,0.000000,regression,True,mean absolute error,0.330667,0.364704,DecisionTreeRegressor()
2,Sepal.Length,Petal.Length,0.550423,regression,True,mean absolute error,1.488667,0.669271,DecisionTreeRegressor()
3,Sepal.Length,Petal.Width,0.431739,regression,True,mean absolute error,0.644667,0.366339,DecisionTreeRegressor()
4,Sepal.Length,Species,0.471649,classification,True,weighted F1,0.353333,0.658333,DecisionTreeClassifier()
5,Sepal.Width,Sepal.Length,0.006966,regression,True,mean absolute error,0.684667,0.679897,DecisionTreeRegressor()
6,Sepal.Width,Sepal.Width,1.000000,predict_itself,True,None,0.000000,1.000000,None
7,Sepal.Width,Petal.Length,0.172375,regression,True,mean absolute error,1.488667,1.232058,DecisionTreeRegressor()
8,Sepal.Width,Petal.Width,0.132858,regression,True,mean absolute error,0.644667,0.559017,DecisionTreeRegressor()
9,Sepal.Width,Species,0.156915,classification,True,weighted F1,0.353333,0.454805,DecisionTreeClassifier()
10,Petal.Length,Sepal.Length,0.525617,regression,True,mean absolute error,0.684667,0.324794,DecisionTreeRegressor()
11,Petal.Length,Sepal.Width,0.052136,regression,True,mean absolute error,0.330667,0.313427,DecisionTreeRegressor()
12,Petal.Length,Petal.Length,1.000000,predict_itself,True,None,0.000000,1.000000,None
13,Petal.Length,Petal.Width,0.744945,regression,True,mean absolute error,0.644667,0.164425,DecisionTreeRegressor()
14,Petal.Length,Species,0.884812,classification,True,weighted F1,0.353333,0.925512,DecisionTreeClassifier()
15,Petal.Width,Sepal.Length,0.383911,regression,True,mean absolute error,0.684667,0.421816,DecisionTreeRegressor()
16,Petal.Width,Sepal.Width,0.254616,regression,True,mean absolute error,0.330667,0.246474,DecisionTreeRegressor()
17,Petal.Width,Petal.Length,0.798274,regression,True,mean absolute error,1.488667,0.300302,DecisionTreeRegressor()
18,Petal.Width,Petal.Width,1.000000,predict_itself,True,None,0.000000,1.000000,None
19,Petal.Width,Species,0.927652,classification,True,weighted F1,0.353333,0.953215,DecisionTreeClassifier()
20,Species,Sepal.Length,0.409634,regression,True,mean absolute error,0.684667,0.404204,DecisionTreeRegressor()
21,Species,Sepal.Width,0.194307,regression,True,mean absolute error,0.330667,0.266416,DecisionTreeRegressor()
22,Species,Petal.Length,0.785393,regression,True,mean absolute error,1.488667,0.319479,DecisionTreeRegressor()
23,Species,Petal.Width,0.755749,regression,True,mean absolute error,0.644667,0.157460,DecisionTreeRegressor()
24,Species,Species,1.000000,predict_itself,True,None,0.000000,1.000000,None